{% set version = "0.4.3" %}

package:
  name: boruta_py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/B/Boruta/Boruta-{{ version }}.tar.gz
  sha256: abd67119bb88c7d1675b0dfc78072e50b5ba1d32b7cc7664258a640ad3a495a4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - numpy >=1.10.4
    - python
    - scikit-learn >=0.17.1
    - scipy >=0.17.0

test:
  imports:
    - boruta

about:
  home: https://github.com/scikit-learn-contrib/boruta_py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python Implementation of Boruta Feature Selection'

extra:
  recipe-maintainers:
    - Ingvar-Y
